[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor_dice = "5qGBhFJhoZUtE1gctQVK9TpHgCVDJw9XEDuw75pcLTNB"
coinflip = "2KR5B1jyJ3XwcWSDjRDZsbgMTNsh2PxyN1yULDS2oCQk"
crash_program = "7EcEa3EkAHWHTnb562rnrXjnBsLmiLgfZ2WL9gtosxyE"
mines = "GMngB79rVBvjrQFEF7b8dnkk7xr3xZQc3kZnQSXNsao2"
plinko = "5rSyAdhghTNwSzVU7PxJwJY7omPGxvQjdtfyn4BxJABr"

[registry]
url = "https://devnet.helius-rpc.com/?api-key=f6c5e503-b09f-49c4-b652-b398c331ecf6"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
